#!/bin/bash
set -e
src=/opt/odoo/custom/src/odoo
dst=/usr/local/bin/odoo
log INFO Installing Odoo from $src

# For development you could want to avoid installing Odoo to speed up build
if [ "$PIP_INSTALL_ODOO" == true ]; then
    args="--no-cache-dir"
    pip install $args --editable $src
else
    log WARNING Blindly symlinking odoo executable
        if [ "$ODOO_VERSION" = "8.0" ]; then
         bin=$src/openerp-server
         ln -s /opt/odoo/custom/src/odoo/openerp-{gevent,server} /usr/local/bin/

     else
         bin=$src/odoo-bin
     fi
    # Cannot check for scripts existence and link all: they probably do not
    # exist yet at build time! Just check Odoo version and act properly.
    ln -s $bin $dst
fi
